# Generated by Django 6.0.5 on 2026-05-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
    ]
